package com.git.programmerr47.vkazam.services;

import android.app.Service;
import android.content.*;
import android.os.Binder;
import android.os.IBinder;
import android.preference.PreferenceManager;
import com.git.programmerr47.vkazam.VkazamApplication;
import com.git.programmerr47.vkazam.model.FingerprintData;
import com.git.programmerr47.vkazam.model.SongData;
import com.git.programmerr47.vkazam.utils.NetworkUtils;
import com.gracenote.mmid.MobileSDK.*;

import java.util.*;

/**
 * Service that provides recording audio from microphone
 * Relates with GraceNote and recieves fingerprint
 * generated by end of listening
 *
 * @author Michael Spitsin
 * @since 2014-04-13
 */
public class MicrophoneRecordingService extends Service implements GNOperationStatusChanged, GNFingerprintResultReady, OnStatusChangedListener {

    // Binder given to clients
    private final IBinder microphoneRecordingBinder = new MicrophoneRecordingBinder();
    private final GNConfig config = ((VkazamApplication) getApplication()).getConfig();
    private final Set<OnStatusChangedListener> onStatusListeners = new HashSet<OnStatusChangedListener>();

    private RecognizeFingerprintService recognizeFingerprintService;
    private boolean isRecording;
    private boolean isRecognizeFingerprintServiceBound;
    int binderCount;

    /**
     * Defines callbacks for service binding, passed to bindService()
     */
    private ServiceConnection connection = new ServiceConnection() {

        @Override
        public void onServiceConnected(ComponentName className,
                                       IBinder service) {
            // We've bound to RecognizeFingerprintService, cast the IBinder and get RecognizeFingerprintService instance
            RecognizeFingerprintService.RecognizeFingerprintBinder binder = (RecognizeFingerprintService.RecognizeFingerprintBinder) service;
            recognizeFingerprintService = binder.getService();
            isRecognizeFingerprintServiceBound = true;
        }

        @Override
        public void onServiceDisconnected(ComponentName arg0) {
            isRecognizeFingerprintServiceBound = false;
        }
    };


    @Override
    public IBinder onBind(Intent intent) {
        binderCount++;
        return microphoneRecordingBinder;
    }

    @Override
    public boolean onUnbind(Intent intent) {
        binderCount--;
        return super.onUnbind(intent);
    }

    public void onCreate() {
        Intent intent = new Intent(this, RecognizeFingerprintService.class);
        bindService(intent, connection, Context.BIND_AUTO_CREATE);
    }

    public void onDestroy() {
        if (isRecognizeFingerprintServiceBound) {
            unbindService(connection);
            isRecognizeFingerprintServiceBound = false;
        }
    }

    /**
     * Records fingerprint one time
     */
    public void recordFingerprint() {
        if (!isRecording) {
            synchronized (this) {
                if (!isRecording) {
                    isRecording = true;
                    GNOperations.fingerprintMIDStreamFromMic(this, config);
                }
            }
        }
    }

    /**
     * Cancels current recording fingerprint
     */
    public void cancelRecording() {
        GNOperations.cancel(this);
        isRecording = false;
    }

    @Override
    public void GNStatusChanged(GNStatus status) {
        onStatusChanged(status.getMessage() + " " + status.getPercentDone() + "%");
    }

    @Override
    public void GNResultReady(GNFingerprintResult gnFingerprintResult) {
        isRecording = false;
        if(gnFingerprintResult.isFailure()) {
            onStatusChanged(String.format("[%d] %s", gnFingerprintResult.getErrCode(), gnFingerprintResult.getErrMessage()));
        } else {
            FingerprintData fingerprint = new FingerprintData(gnFingerprintResult.getFingerprintData(), new Date());
            FingerprintWrapper wrapper = new FingerprintWrapper(fingerprint, this, FingerprintWrapper.RECOGNIZE_PRIORITY_HIGHEST);
            recognizeFingerprintService.recognize(wrapper);
        }
    }

    public void addOnStatusChangedListener(OnStatusChangedListener listener) {
        onStatusListeners.add(listener);
    }

    public void removeOnStatusChangedListener(OnStatusChangedListener listener) {
        onStatusListeners.remove(listener);
    }

    @Override
    public void onStatusChanged(String status) {
        for (OnStatusChangedListener listener : onStatusListeners) {
            listener.onStatusChanged(status);
        }
    }

    @Override
    public void onResultStatus(SongData data) {
        for (OnStatusChangedListener listener : onStatusListeners) {
            listener.onResultStatus(data);
        }

        if (binderCount == 0) {
            stopSelf();
        }
    }

    /**
     * Class used for the client Binder.  Because we know this service always
     * runs in the same process as its clients, we don't need to deal with IPC.
     */
    public class MicrophoneRecordingBinder extends Binder {

        /**
         * @return instance of RecognizeFingerprintService so clients can call public methods
         */
        MicrophoneRecordingService getService() {
            return MicrophoneRecordingService.this;
        }
    }
}
